// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sobol_g_cpp
NumericVector sobol_g_cpp(NumericMatrix X, NumericVector a);
RcppExport SEXP _Sobol4R_sobol_g_cpp(SEXP XSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(sobol_g_cpp(X, a));
    return rcpp_result_gen;
END_RCPP
}
// sobol_g2_cpp
NumericVector sobol_g2_cpp(NumericMatrix X, NumericVector a);
RcppExport SEXP _Sobol4R_sobol_g2_cpp(SEXP XSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(sobol_g2_cpp(X, a));
    return rcpp_result_gen;
END_RCPP
}
// sobol_g2_additive_noise_cpp
NumericVector sobol_g2_additive_noise_cpp(NumericMatrix X, double sd, NumericVector a);
RcppExport SEXP _Sobol4R_sobol_g2_additive_noise_cpp(SEXP XSEXP, SEXP sdSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(sobol_g2_additive_noise_cpp(X, sd, a));
    return rcpp_result_gen;
END_RCPP
}
// sobol_g2_qoi_mean_cpp
NumericVector sobol_g2_qoi_mean_cpp(NumericMatrix X, int nrep, double sd, NumericVector a);
RcppExport SEXP _Sobol4R_sobol_g2_qoi_mean_cpp(SEXP XSEXP, SEXP nrepSEXP, SEXP sdSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(sobol_g2_qoi_mean_cpp(X, nrep, sd, a));
    return rcpp_result_gen;
END_RCPP
}
// sobol_g2_with_covariate_noise_cpp
NumericVector sobol_g2_with_covariate_noise_cpp(NumericMatrix X, NumericVector a);
RcppExport SEXP _Sobol4R_sobol_g2_with_covariate_noise_cpp(SEXP XSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(sobol_g2_with_covariate_noise_cpp(X, a));
    return rcpp_result_gen;
END_RCPP
}
// sobol_g2_qoi_covariate_mean_cpp
NumericVector sobol_g2_qoi_covariate_mean_cpp(NumericMatrix X, int nrep, NumericVector a);
RcppExport SEXP _Sobol4R_sobol_g2_qoi_covariate_mean_cpp(SEXP XSEXP, SEXP nrepSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(sobol_g2_qoi_covariate_mean_cpp(X, nrep, a));
    return rcpp_result_gen;
END_RCPP
}
// ishigami_cpp
Rcpp::NumericVector ishigami_cpp(Rcpp::NumericVector x1, Rcpp::NumericVector x2, Rcpp::NumericVector x3, double a, double b);
RcppExport SEXP _Sobol4R_ishigami_cpp(SEXP x1SEXP, SEXP x2SEXP, SEXP x3SEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x3(x3SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(ishigami_cpp(x1, x2, x3, a, b));
    return rcpp_result_gen;
END_RCPP
}
// one_unit_cpp
NumericVector one_unit_cpp(double lambda1, double lambda2, double lambda3, double p1, double p2);
RcppExport SEXP _Sobol4R_one_unit_cpp(SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP lambda3SEXP, SEXP p1SEXP, SEXP p2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda3(lambda3SEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    rcpp_result_gen = Rcpp::wrap(one_unit_cpp(lambda1, lambda2, lambda3, p1, p2));
    return rcpp_result_gen;
END_RCPP
}
// process_fun_indiv_cpp
double process_fun_indiv_cpp(NumericVector x_indiv, int M);
RcppExport SEXP _Sobol4R_process_fun_indiv_cpp(SEXP x_indivSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_indiv(x_indivSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(process_fun_indiv_cpp(x_indiv, M));
    return rcpp_result_gen;
END_RCPP
}
// process_fun_row_wise_cpp
NumericVector process_fun_row_wise_cpp(NumericMatrix X, int M);
RcppExport SEXP _Sobol4R_process_fun_row_wise_cpp(SEXP XSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(process_fun_row_wise_cpp(X, M));
    return rcpp_result_gen;
END_RCPP
}
// process_fun_mean_to_M_cpp
NumericVector process_fun_mean_to_M_cpp(NumericMatrix X, int M, int nrep);
RcppExport SEXP _Sobol4R_process_fun_mean_to_M_cpp(SEXP XSEXP, SEXP MSEXP, SEXP nrepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    rcpp_result_gen = Rcpp::wrap(process_fun_mean_to_M_cpp(X, M, nrep));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Sobol4R_sobol_g_cpp", (DL_FUNC) &_Sobol4R_sobol_g_cpp, 2},
    {"_Sobol4R_sobol_g2_cpp", (DL_FUNC) &_Sobol4R_sobol_g2_cpp, 2},
    {"_Sobol4R_sobol_g2_additive_noise_cpp", (DL_FUNC) &_Sobol4R_sobol_g2_additive_noise_cpp, 3},
    {"_Sobol4R_sobol_g2_qoi_mean_cpp", (DL_FUNC) &_Sobol4R_sobol_g2_qoi_mean_cpp, 4},
    {"_Sobol4R_sobol_g2_with_covariate_noise_cpp", (DL_FUNC) &_Sobol4R_sobol_g2_with_covariate_noise_cpp, 2},
    {"_Sobol4R_sobol_g2_qoi_covariate_mean_cpp", (DL_FUNC) &_Sobol4R_sobol_g2_qoi_covariate_mean_cpp, 3},
    {"_Sobol4R_ishigami_cpp", (DL_FUNC) &_Sobol4R_ishigami_cpp, 5},
    {"_Sobol4R_one_unit_cpp", (DL_FUNC) &_Sobol4R_one_unit_cpp, 5},
    {"_Sobol4R_process_fun_indiv_cpp", (DL_FUNC) &_Sobol4R_process_fun_indiv_cpp, 2},
    {"_Sobol4R_process_fun_row_wise_cpp", (DL_FUNC) &_Sobol4R_process_fun_row_wise_cpp, 2},
    {"_Sobol4R_process_fun_mean_to_M_cpp", (DL_FUNC) &_Sobol4R_process_fun_mean_to_M_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_Sobol4R(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
