# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sobol_g_cpp <- function(X, a) {
    .Call(`_Sobol4R_sobol_g_cpp`, X, a)
}

sobol_g2_cpp <- function(X, a) {
    .Call(`_Sobol4R_sobol_g2_cpp`, X, a)
}

sobol_g2_additive_noise_cpp <- function(X, sd = 1.0, a = as.numeric( c(0.0, 1.0, 4.5, 9.0, 99.0, 99.0, 99.0, 99.0))) {
    .Call(`_Sobol4R_sobol_g2_additive_noise_cpp`, X, sd, a)
}

sobol_g2_qoi_mean_cpp <- function(X, nrep = 1000L, sd = 1.0, a = as.numeric( c(0.0, 1.0, 4.5, 9.0, 99.0, 99.0, 99.0, 99.0))) {
    .Call(`_Sobol4R_sobol_g2_qoi_mean_cpp`, X, nrep, sd, a)
}

sobol_g2_with_covariate_noise_cpp <- function(X, a = as.numeric( c(0.0, 1.0, 4.5, 9.0, 99.0, 99.0, 99.0, 99.0))) {
    .Call(`_Sobol4R_sobol_g2_with_covariate_noise_cpp`, X, a)
}

sobol_g2_qoi_covariate_mean_cpp <- function(X, nrep = 1000L, a = as.numeric( c(0.0, 1.0, 4.5, 9.0, 99.0, 99.0, 99.0, 99.0))) {
    .Call(`_Sobol4R_sobol_g2_qoi_covariate_mean_cpp`, X, nrep, a)
}

ishigami_cpp <- function(x1, x2, x3, a, b) {
    .Call(`_Sobol4R_ishigami_cpp`, x1, x2, x3, a, b)
}

one_unit_cpp <- function(lambda1, lambda2, lambda3, p1, p2) {
    .Call(`_Sobol4R_one_unit_cpp`, lambda1, lambda2, lambda3, p1, p2)
}

process_fun_indiv_cpp <- function(x_indiv, M = 50L) {
    .Call(`_Sobol4R_process_fun_indiv_cpp`, x_indiv, M)
}

process_fun_row_wise_cpp <- function(X, M = 50L) {
    .Call(`_Sobol4R_process_fun_row_wise_cpp`, X, M)
}

process_fun_mean_to_M_cpp <- function(X, M = 50L, nrep = 10L) {
    .Call(`_Sobol4R_process_fun_mean_to_M_cpp`, X, M, nrep)
}

